// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	parking "github.com/adityatresnobudi/parking-system/parking"
	mock "github.com/stretchr/testify/mock"
)

// Subscriber is an autogenerated mock type for the Subscriber type
type Subscriber struct {
	mock.Mock
}

// NotifyLotIsFull provides a mock function with given fields: _a0
func (_m *Subscriber) NotifyLotIsFull(_a0 *parking.Lot) {
	_m.Called(_a0)
}

// NotifyLotIsNotFull provides a mock function with given fields: _a0
func (_m *Subscriber) NotifyLotIsNotFull(_a0 *parking.Lot) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewSubscriber interface {
	mock.TestingT
	Cleanup(func())
}

// NewSubscriber creates a new instance of Subscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSubscriber(t mockConstructorTestingTNewSubscriber) *Subscriber {
	mock := &Subscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
